Develop
nicolasmarino99/New-York-Times-article-page-clone pull request #1
Opened 2019-07-17 20:25 UTC by nicolasmarino99

Awaiting for reply.

2019-07-17 22:41 UTC, samgaco requested changes
Hi dream team _(readme file)_ :laughing: 

The project looks great :muscle:  although there are some things to address before proceeding;

* First and foremost, the branch has a conflict in the README file, so you should resolve it before submitting for a code review again.
* The New York times logo in the center of the navigation bar should be a link.
* The New York times logo at the top left corner of the footer should be a link.
* There should be a _go to homepage_ link on the top right corner of the footer
* The sections **More in Space & Cosmos** and **Editors’ Picks** should have the titles as links.
* It lacks the two sections and the right side of the site;

> ![signup](https://user-images.githubusercontent.com/34820784/61416246-5a7a6200-a8f3-11e9-98f2-bf3154398985.jpg)
> ![picks](https://user-images.githubusercontent.com/34820784/61416251-5c442580-a8f3-11e9-8b74-304258daea47.jpg)
> 


* All images and videos should be enclosed by a `<figure>` tag with a `<figcaption> `for the description. You can find more information about it here: https://www.w3schools.com/tags/tag_figcaption.asp

* The `<figcaption>` and `<figure>` tags should be also used for the left side of additional links. Following this structure:

```
<figure>
  <img src="image.jpg" alt="img">
  <figcaption>Title of the article.</figcaption>
</figure>
```

* Any section including paragraphs in your project should be enclosed within the` <section> `tag. In the case of the "Editor's picks" and the "Sign up" button they should also include the `<aside>` tag. Learn more about it here: https://www.w3schools.com/html/html5_semantic_elements.asp (you seem to have addressed this part already, but the code is commented in the pull request)

That would be it. Please :pray: commit these changes and submit again for a code review. :muscle:

2019-07-17 22:41 UTC, samgaco commented on index.html
> +
You have these two sections commented, which should be on the right side of the website.

2019-07-17 22:41 UTC, samgaco commented on styles/styles.css
> +
It's better not to have commented code.

2019-07-19 04:56 UTC, bolah2009 approved these changes
# Congratulations Team! :tada:

You've done an awesome Job :muscle:

#### Important: I strongly recommend updating your readme file with more details about the project, live version link, assignment link and screenshot of features implemented among other things you would like people visiting the Github link of this project to know about.

Good luck with your next project
Keep it up :star2:

Cheers
Bola

2019-07-19 16:43 UTC, merged